### ISSUE TITLE
Add code to kill page load if keys file not valid

### ISSUE THREAD

**Issue by jackhughesweb** [teamscreamingsquaredinosaur/prettyroute#11]
Fixed the bug, should I add code to kill page load with an error if keys file is invalid?

@JoeMalt @TechyByte @Deezo @lucywalsh

**Comment by jackhughesweb** [comment]
Fixed in 211e1bd0942a5558fad1dbfd3e873686827e4273

**Comment by lucywalsh** [comment]
Well done! Sounds good to me
