### ISSUE TITLE
Add options

### ISSUE THREAD

**Issue by jackhughesweb** [teamscreamingsquaredinosaur/prettyroute#14]
- Motorways on/off

**Comment by JoeMalt** [comment]
Maybe custom radius,but probably keep it proportional to journey length, once @TechyByte has implemented that

**Comment by JoeMalt** [comment]
Options are here:
https://developers.google.com/places/supported_types?hl=en

Probably implement:
* zoo
* museum
* casino
* church
* art_gallery and museum (maybe together)
* aquarium
* cafe
* amusement_park
* mosque
* synagogue

**Comment by JoeMalt** [comment]
If we do want to avoid highways, that can be done https://developers.google.com/maps/documentation/directions/intro#RequestParameters

**Comment by JoeMalt** [comment]
A few presets:

* Culture: museum, art_gallery
* Kids: zoo, amusement_park, aquarium
* @Deezo 's gay night out mode: bar, beauty_salon, clothing_store, shoe_store, night_clud

**Comment by JoeMalt** [comment]
This is malfunctioning again
