### ISSUE TITLE
Optimise bandwidth usage

### ISSUE THREAD

**Issue by JoeMalt** [teamscreamingsquaredinosaur/prettyroute#18]
Homepage alone is approx. 2MB (need to compress the background image and/or implement @lucywalsh's map

Loading a route can be 3-7MB, but a lot of this is just Google Maps and there's not a lot we can do about it

**Comment by jackhughesweb** [comment]
Would be nice to optimise the backend code too to reduce page load time

**Comment by TechyByte** [comment]
Especially given the server takes 2 seconds or more just to begin to return a response.

**Comment by TechyByte** [comment]
Prefetching results would be good

**Comment by jackhughesweb** [comment]
I may try to rewrite into a single page application and use javascript to access /api/getRoute.php

**Comment by jackhughesweb** [comment]
@TechyByte The code on the backend needs to be optimised too

**Comment by jackhughesweb** [comment]
@TechyByte could you remove the preloader? I'll clean up the code instead

**Comment by TechyByte** [comment]
Are you sure to remove it, if one of our scripts hangs/lags or an API call times out, it'd be better to have a loading page.

**Comment by jackhughesweb** [comment]
With the PHP code, I could just request the data over javascript, then show a loading animation (simple spinner?) until the data is returned.

**Comment by jackhughesweb** [comment]
I'd rather write code for loading than use a third party loader

**Comment by jackhughesweb** [comment]
Moved to a single-page app and removed the large background
