### ISSUE TITLE
Preloading screen

### ISSUE THREAD

**Issue by TechyByte** [teamscreamingsquaredinosaur/prettyroute#23]
This is currently active as soon as data transmission begins, but unfortunately doesn't work fully as of yet due to the majority of latency being caused by server(php)-side processing

**Comment by jackhughesweb** [comment]
Could we not use the javascript preloading animation? I'll clean and optimise the front end code for you instead

**Comment by jackhughesweb** [comment]
I've converted it to a single page application and have removed the large background which has reduced the page load time, but the server-side processing still takes a long time - presumably because of the polyline to latlonarray function?

**Comment by TechyByte** [comment]
I can't imagine that function takes too long

**Comment by jackhughesweb** [comment]
Is it possible to get a graph on php loading times like DevTools does for JavaScript?
