### ISSUE TITLE
Suggestion buttons break at higher zoom levels

### ISSUE THREAD

**Issue by JoeMalt** [teamscreamingsquaredinosaur/prettyroute#29]
## In Chrome
At 100%
![screen shot 2015-08-04 at 22 15 58](https://cloud.githubusercontent.com/assets/1771291/9073005/7d120634-3af6-11e5-9959-1d7c93ea3cb0.png)

At 110%
![screen shot 2015-08-04 at 22 16 11](https://cloud.githubusercontent.com/assets/1771291/9073007/8099d778-3af6-11e5-9b17-8baaa097b52b.png)

## In Safari
At 100%
![screen shot 2015-08-04 at 22 18 58](https://cloud.githubusercontent.com/assets/1771291/9073088/f213e48e-3af6-11e5-9a11-72862fdeb058.png)

At 110%
![screen shot 2015-08-04 at 22 19 06](https://cloud.githubusercontent.com/assets/1771291/9073093/fa349e24-3af6-11e5-878d-acff21623c27.png)

**Comment by JoeMalt** [comment]
Firefox seems to handle this slightly better

**Comment by jackhughesweb** [comment]
Not sure why this is happening, as the buttons are just standard UI elements, but I'll take a look

**Comment by jackhughesweb** [comment]
@JoeMalt can't reproduce, what are the browser versions/devices that this is happening on?

**Comment by JoeMalt** [comment]
Chrome: Version 44.0.2403.125 (64-bit) on a MacBook Air at 1440x900

**Comment by jackhughesweb** [comment]
I can now reproduce this, but I still can't see what is going on here.

**Comment by jackhughesweb** [comment]
It looks like it is an existing bug with the browser/OS and is not our fault.
Chrome on Yosemite at 110% zoom:
![screen shot 2015-09-04 at 20 11 55](https://cloud.githubusercontent.com/assets/1905799/9692478/42cd5a7e-5341-11e5-9e00-5cb2a4e6cc8d.png)
