### ISSUE TITLE
Going back to map view doesn't work

### ISSUE THREAD

**Issue by JoeMalt** [teamscreamingsquaredinosaur/prettyroute#39]
Since we switched from redirecting to getRoute.php to using an API call and rendering the map in index.php, we now have the issue that the URL doesn't change, so when you click on a "Details" link or otherwise navigate away from the map, then go back, you get the index page instead.

I see 2 ways to fix this:

##Easy way
Open all "details" links etc. in a new window (target=_blank). I'm happy to do this ASAP if we want to.

##Hard(er) way
Make the URL change (fragments) when loading the map, so that it can be re-rendered when the page is reloaded. This has the advantage of almost being a permalink to a particular route (although not entirely because of the whole random generation thing).

Thoughts?

**Comment by jackhughesweb** [comment]
My idea was to use the javascript history api to make it look as though we have loaded a new page, e.g. the URL changes to /route?from.... and if a user goes to /route, just load the index.php file and use a bit of magical javascript to detect this and automatically load the route.

I was also thinking of a shareable URL feature which is different to this issue, where the URL gives the same places in the results on every load.

**Comment by JoeMalt** [comment]
Looks like @TechyByte implemented the "easy workaround" a while ago but it doesn't seem to be working (Chrome on Mac) https://github.com/teamscreamingsquaredinosaur/prettyroute/commit/ef4c0c6e2954778380285156396c53ad05f20201

**Comment by JoeMalt** [comment]
@jackhughesweb that all sounds good to me, the permalink feature is a good idea too
